

M_OFS = 480 #Matrix register offset

REGISTERS_INFO = {
    #  if min=max=0, read-only, min=max=1 Self-clearing)
    # regs: max number of the register offset+1
                                 "ASIC_ID": {"addr":         0, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max":          0},
                       "OUTPUT_MUX_SELECT": {"addr":         1, "loc":  0, "mask":     0xFFFF, "regs":   1, "min": 0, "max":          2},
                  "POST_PROCESSING_SELECT": {"addr":         1, "loc": 16, "mask": 0xFFFF0000, "regs":   1, "min": 0, "max":       0xFF},
                            "TRIGGER_TYPE": {"addr":         2, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
                     "SERIAL_READOUT_TYPE": {"addr":         3, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
         "TRIGGER_ENERGY_INTEGRATION_TIME": {"addr":         4, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
              "PIXELS_DARK_COUNT_RESET_EN": {"addr":         5, "loc":  0, "mask":        0x1, "regs":   1, "min": 0, "max":          1},
                   "READ_UNTRIGGERED_TDCS": {"addr":         5, "loc":  1, "mask":        0x2, "regs":   1, "min": 0, "max":          1},
   "TRIGGER_EVENT_DRIVEN_COLUMN_THRESHOLD": {"addr":         6, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
              "TRIGGER_TIME_DRIVEN_PERIOD": {"addr":         7, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
         "TRIGGER_WINDOW_DRIVEN_THRESHOLD": {"addr":         8, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
                            "READOUT_MODE": {"addr":         9, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
                         "TDC_GATING_MODE": {"addr":        10, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
                       "TIME_BIN_BOUNDS_0": {"addr":        11, "loc":  0, "mask":     0xFFFF, "regs":   1, "min": 0, "max":     0xFFFF},
                     "TIME_BIN_BOUNDS_0_1": {"addr":        11, "loc": 16, "mask": 0xFFFF0000, "regs":   1, "min": 0, "max":     0xFFFF},
                     "TIME_BIN_BOUNDS_1_2": {"addr":        12, "loc":  0, "mask":     0xFFFF, "regs":   1, "min": 0, "max":     0xFFFF},
                       "TIME_BIN_BOUNDS_2": {"addr":        12, "loc": 16, "mask": 0xFFFF0000, "regs":   1, "min": 0, "max":     0xFFFF},
                         "TDC_STOP_SIGNAL": {"addr":        13, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
                              "DCA_ENABLE": {"addr":        14, "loc":  0, "mask":        0x1, "regs":   1, "min": 0, "max":          1},
                           "DCA_THRESHOLD": {"addr":        14, "loc":  1, "mask":       0x1E, "regs":   1, "min": 0, "max":         15},
                         "PLL_ENABLE_TEST": {"addr":        15, "loc":  0, "mask":        0x1, "regs":   1, "min": 0, "max":          1},
                         "PLL_SELECT_TEST": {"addr":        15, "loc":  1, "mask":        0x2, "regs":   1, "min": 0, "max":          1},
            "PLL_DISABLE_EXTERNAL_TRIGGER": {"addr":        15, "loc":  2, "mask":        0x4, "regs":   1, "min": 0, "max":          1},
                        "PLL_SFTWR_RST_EN": {"addr":        15, "loc":  3, "mask":        0x8, "regs":   1, "min": 0, "max":          1},
                           "PLL_SFTWR_RST": {"addr":        15, "loc":  4, "mask":       0x10, "regs":   1, "min": 0, "max":          1},
                              "PLL_ENABLE": {"addr":        15, "loc":  5, "mask":       0x20, "regs":   1, "min": 0, "max":          1},
                    "PLL_TEST_SECTION_MUX": {"addr":        15, "loc": 16, "mask": 0xFFFF0000, "regs":   1, "min": 0, "max":     0xFFFF},
                      "DCR_INTERVAL_WIDTH": {"addr":        16, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
                    "DCR_INTERVAL_SPACING": {"addr":        17, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
                   "WINDOW_BIT_CONFIG_LOW": {"addr":        18, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max":          1},
                  "WINDOW_BIT_CONFIG_HIGH": {"addr":        18, "loc":  7, "mask":       0X80, "regs":   1, "min": 0, "max":          1},
               "WINDOW_BIT_REF_CONFIG_LOW": {"addr":        18, "loc":  8, "mask":      0x100, "regs":   1, "min": 0, "max":          1},
              "WINDOW_BIT_REF_CONFIG_HIGH": {"addr":        18, "loc":  9, "mask":     0x8000, "regs":   1, "min": 0, "max":          1},
                  "INDIVIDUAL_SPAD_ACCESS": {"addr":        19, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
    "EVENT_DETECTION_BIT_INTEGRATION_TIME": {"addr":        20, "loc":  0, "mask":        0x1, "regs":   1, "min": 0, "max":          1},
    "EVENT_DETECTION_BIT_COLUMN_THRESHOLD": {"addr":        20, "loc": 12, "mask":     0x1000, "regs":   1, "min": 0, "max":          1},
    "ENERGY_DISCRIMINATION_TIME_THRESHOLD": {"addr":        21, "loc":  0, "mask":     0xFFFF, "regs":   1, "min": 0, "max":     0xFFFF},
      "ENERGY_DISCRIMINATION_PHOTON_ORDER": {"addr":        21, "loc": 16, "mask":   0x3F0000, "regs":   1, "min": 0, "max":       0x3F},
     "ENERGY_DISCRIMINATION_ALWAYS_OUTPUT": {"addr":        21, "loc": 22, "mask":   0x400000, "regs":   1, "min": 0, "max":          1},

               "PIXEL_DISABLE_TDC_ARRAY_0": {"addr":        22, "loc":  0, "mask": 0xFFFFFFFF, "regs":   2, "min": 0, "max": 0xFFFFFFFF},
            "PIXEL_DISABLE_QUENCH_ARRAY_0": {"addr":        24, "loc":  0, "mask": 0xFFFFFFFF, "regs":   7, "min": 0, "max": 0xFFFFFFFF},
        "DISABLE_EXTERNAL_TRIGGER_ARRAY_0": {"addr":        31, "loc":  0, "mask": 0xFFFFFFFF, "regs":   7, "min": 0, "max": 0xFFFFFFFF},
          "TIME_CONVERSION_CLOCK_PERIOD_0": {"addr":        38, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
           "DARK_COUNT_FILTER_DELTA_0_1_0": {"addr":        40, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
           "DARK_COUNT_FILTER_DELTA_2_3_0": {"addr":        41, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
           "DARK_COUNT_FILTER_DELTA_4_5_0": {"addr":        42, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
             "REGISTER_WEIGHTED_AVERAGE_0": {"addr":        43, "loc":  0, "mask": 0xFFFFFFFF, "regs":  16, "min": 0, "max": 0xFFFFFFFF},
              "COARSE_BIAS_LOOKUP_TABLE_0": {"addr":        59, "loc":  0, "mask": 0xFFFFFFFF, "regs": 196, "min": 0, "max": 0xFFFFFFFF},
             "COARSE_SLOPE_LOOKUP_TABLE_0": {"addr":       255, "loc":  0, "mask": 0xFFFFFFFF, "regs":  98, "min": 0, "max": 0xFFFFFFFF},
                       "SPAD_LOCAL_SKEW_0": {"addr":       353, "loc":  0, "mask": 0xFFFFFFFF, "regs":  98, "min": 0, "max": 0xFFFFFFFF},
             "TDC_LOCAL_CORRECTION_FINE_0": {"addr":       451, "loc":  0, "mask": 0xFFFFFFFF, "regs":  25, "min": 0, "max": 0xFFFFFFFF},
           "TDC_LOCAL_CORRECTION_COARSE_0": {"addr":       476, "loc":  0, "mask": 0xFFFFFFFF, "regs":  25, "min": 0, "max": 0xFFFFFFFF},

               "PIXEL_DISABLE_TDC_ARRAY_1": {"addr":  22+M_OFS, "loc":  0, "mask": 0xFFFFFFFF, "regs":   2, "min": 0, "max": 0xFFFFFFFF},
            "PIXEL_DISABLE_QUENCH_ARRAY_1": {"addr":  24+M_OFS, "loc":  0, "mask": 0xFFFFFFFF, "regs":   7, "min": 0, "max": 0xFFFFFFFF},
        "DISABLE_EXTERNAL_TRIGGER_ARRAY_1": {"addr":  31+M_OFS, "loc":  0, "mask": 0xFFFFFFFF, "regs":   7, "min": 0, "max": 0xFFFFFFFF},
          "TIME_CONVERSION_CLOCK_PERIOD_1": {"addr":  38+M_OFS, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
           "DARK_COUNT_FILTER_DELTA_0_1_1": {"addr":  40+M_OFS, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
           "DARK_COUNT_FILTER_DELTA_2_3_1": {"addr":  41+M_OFS, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
           "DARK_COUNT_FILTER_DELTA_4_5_1": {"addr":  42+M_OFS, "loc":  0, "mask": 0xFFFFFFFF, "regs":   1, "min": 0, "max": 0xFFFFFFFF},
             "REGISTER_WEIGHTED_AVERAGE_1": {"addr":  43+M_OFS, "loc":  0, "mask": 0xFFFFFFFF, "regs":  16, "min": 0, "max": 0xFFFFFFFF},
              "COARSE_BIAS_LOOKUP_TABLE_1": {"addr":  59+M_OFS, "loc":  0, "mask": 0xFFFFFFFF, "regs": 196, "min": 0, "max": 0xFFFFFFFF},
             "COARSE_SLOPE_LOOKUP_TABLE_1": {"addr": 255+M_OFS, "loc":  0, "mask": 0xFFFFFFFF, "regs":  98, "min": 0, "max": 0xFFFFFFFF},
                       "SPAD_LOCAL_SKEW_1": {"addr": 353+M_OFS, "loc":  0, "mask": 0xFFFFFFFF, "regs":  98, "min": 0, "max": 0xFFFFFFFF},
             "TDC_LOCAL_CORRECTION_FINE_1": {"addr": 451+M_OFS, "loc":  0, "mask": 0xFFFFFFFF, "regs":  25, "min": 0, "max": 0xFFFFFFFF},
           "TDC_LOCAL_CORRECTION_COARSE_1": {"addr": 476+M_OFS, "loc":  0, "mask": 0xFFFFFFFF, "regs":  25, "min": 0, "max": 0xFFFFFFFF}

}